Repository jenkinsci/workflow-api-plugin, pull requests merged in 2021-12, with the labels that each got.

#183 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: maintenance

#187 [JENKINS-40161] Handle exceptions from `StepExecution.onResume`
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
Labels: enhancement

#188 [JENKINS-67351] Avoid deadlock when resuming Pipelines in some cases
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
Labels: bug
