Repository jenkinsci/workflow-api-plugin, pull requests merged in 2021-11, with the labels that each got.

#181 Update Dependabot configuration
  .github/dependabot.yml
Labels: chore, maintenance

#182 Use container agent in `Jenkinsfile`
  Jenkinsfile
Labels: maintenance

#177 Reduce usages of Guava
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowCopier.java
Labels: maintenance

#178 [JENKINS-67164] Call StepExecution.onResume directly from WorkflowRun.onLoad rather than via FlowExecutionList.ItemListenerImpl to ensure step resumption
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListTest.java
Labels: bug
