Repository jenkinsci/workflow-api-plugin, pull requests merged in 2022-01, with the labels that each got.

#190 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/FilePathUtils.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/ArgumentsAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/ErrorAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/QueueItemAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/TagsAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/ThreadNameAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/WarningAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/WorkspaceAction.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/DurabilityHintProvider.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowDurabilityHint.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListener.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionOwner.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/GlobalDefaultFlowDurabilityLevel.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/StepListener.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/BlockEndNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/BlockStartNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/FlowNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/GraphLookupView.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/StandardGraphLookupView.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/StepNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/AbstractFlowScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/BlockChunkFinder.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ChunkFinder.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/DepthFirstScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/Filterator.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FilteratorImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowChunkWithContext.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowNodeVisitor.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowScanningUtils.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LabelledChunkFinder.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearBlockHoppingScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/MemoryFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/NodeStepNamePredicate.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/NodeStepTypePredicate.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ParallelFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ParallelMemoryFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/SimpleChunkVisitor.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/StandardChunkVisitor.java
  src/main/java/org/jenkinsci/plugins/workflow/log/LogStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/log/LogStorageFactory.java
  src/main/java/org/jenkinsci/plugins/workflow/log/TaskListenerDecorator.java
  src/main/java/org/jenkinsci/plugins/workflow/pickles/PickleFactory.java
  src/main/java/org/jenkinsci/plugins/workflow/visualization/table/FlowNodeViewColumnDescriptor.java
  src/test/java/org/jenkinsci/plugins/workflow/ArtifactManagerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowTestUtils.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/NoOpChunkFinder.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/TestVisitor.java
Labels: dependencies

#185 Code clean-up
  src/main/java/org/jenkinsci/plugins/workflow/FilePathUtils.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/ArgumentsAction.java
  src/main/java/org/jenkinsci/plugins/workflow/actions/TagsAction.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowCopier.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionOwner.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/GlobalDefaultFlowDurabilityLevel.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/FlowNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graph/FlowStartNode.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FilteratorImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowScanningUtils.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearBlockHoppingScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/MemoryFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ParallelFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ParallelMemoryFlowChunk.java
  src/main/java/org/jenkinsci/plugins/workflow/log/BrokenLogStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/log/BufferedBuildListener.java
  src/main/java/org/jenkinsci/plugins/workflow/log/ConsoleAnnotators.java
  src/main/java/org/jenkinsci/plugins/workflow/log/DelayBufferedOutputStream.java
  src/main/java/org/jenkinsci/plugins/workflow/log/FileLogStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/log/GCFlushedOutputStream.java
  src/main/java/org/jenkinsci/plugins/workflow/log/LogStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/log/TaskListenerDecorator.java
  src/test/java/org/jenkinsci/plugins/workflow/ArtifactManagerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/DirectArtifactManagerFactory.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/DurabilityBasicsTest.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListTest.java
  src/test/java/org/jenkinsci/plugins/workflow/graph/FlowNodeTest.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowScannerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowTestUtils.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScannerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/TestVisitor.java
  src/test/java/org/jenkinsci/plugins/workflow/log/LogStorageTestBase.java
Labels: chore

#192 Prepare for icon removal from core
  src/main/resources/org/jenkinsci/plugins/workflow/graph/FlowNode/sidepanel.jelly
Labels: maintenance

#198 Revert fixes related to JENKINS-67351 and JENKINS-67164
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListTest.java
Labels: bug

#197 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/AbstractFlowScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/DepthFirstScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FilteratorImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearBlockHoppingScanner.java
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/LinearScanner.java
Labels: dependencies

#195 Update parent, baseline, BOM
  pom.xml
Labels: dependencies

#184 Fix typos
  docs/flowgraph.md
Labels: documentation
