Repository jenkinsci/workflow-api-plugin, pull requests merged in 2022-06, with the labels that each got.

#221 [JENKINS-67164] Call `StepExecution.onResume` in response to `WorkflowRun.onLoad` not `FlowExecutionList.ItemListenerImpl`
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListener.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListTest.java
Labels: breaking

#226 Require 2.332.x
  pom.xml
Labels: bug

#166 allower downstream plugin to adjust the apply order of TaskListenerDecorator created from TaskListenerDecorator.Factory
  src/main/java/org/jenkinsci/plugins/workflow/log/TaskListenerDecorator.java
  src/test/java/org/jenkinsci/plugins/workflow/log/TaskListenerDecoratorOrderTest.java
Labels: enhancement
