Repository jenkinsci/workflow-api-plugin, pull requests merged in 2023-09, with the labels that each got.

#306 Add warning to ForkScanner Javadoc describing potential issues when using it with multiple heads
  src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScanner.java
  src/test/java/org/jenkinsci/plugins/workflow/graphanalysis/ForkScannerTest.java
Labels: documentation

#309 [JENKINS-71970] Potentially solve memory leak
  src/main/java/org/jenkinsci/plugins/workflow/log/BufferedBuildListener.java
Labels: bug

#311 [JENKINS-71970] Memory leak involving `BufferedBuildListener`
  src/main/java/org/jenkinsci/plugins/workflow/log/BufferedBuildListener.java
Labels: bug

#312 Allow location of `FlowExecutionList.xml` to be overridden
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
Labels: developer
