Repository jenkinsci/workflow-api-plugin, pull requests merged in 2024-05, with the labels that each got.

#326 Bump baseline to pick up `ProxyException` fix
  pom.xml
  src/test/java/org/jenkinsci/plugins/workflow/actions/ErrorActionTest.java
Labels: dependencies

#328 `ErrorAction.findOrigin` failures due to `ProxyException`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/actions/ErrorAction.java
  src/test/java/org/jenkinsci/plugins/workflow/actions/ErrorActionTest.java
Labels: bug

#332 Migrate from Apache Commons Compress to Ant
  src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
Labels: developer

#331 Use Java 7 versions of `GZIPInputStream` and `GZIPOutputStream`
  src/main/java/org/jenkinsci/plugins/workflow/log/ConsoleAnnotators.java
Labels: developer
