Repository jenkinsci/workflow-api-plugin, pull requests merged in 2025-01, with the labels that each got.

#367 Require 2.452.4
  pom.xml
Labels: dependencies

#369 Removing `FlowExecution.notifyShutdown`
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionOwner.java
Labels: chore

#370 `FlowExecutionList.Storage`
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionOwner.java
Labels: developer

#368 Resume Pipeline builds asynchronously
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
Labels: enhancement

#372 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/flow/GlobalDefaultFlowDurabilityLevel.java
  src/main/java/org/jenkinsci/plugins/workflow/log/ConsoleAnnotators.java
Labels: internal

#373 `StepExecutionIterator.accept`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
  src/test/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionListTest.java
Labels: developer
